-- NutriLog — 0001 initial schema (MVP)
-- Run this in the Supabase SQL editor.
--
-- Notes:
--  * IDs are generated by the app (docs/database.md: "UUID generados desde la aplicación").
--  * updated_at is controlled by the APP, not by a DB trigger: last-write-wins
--    sync relies on the client timestamp winning (docs/database.md).
--  * All tables are RLS-protected by user_id.

-- Units (catalog)
create table if not exists public.units (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Categories (catalog)
create table if not exists public.categories (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Brands (catalog)
create table if not exists public.brands (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Products
create table if not exists public.products (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  brand_id uuid references public.brands (id) on delete set null,
  category_id uuid references public.categories (id) on delete set null,
  serving_amount numeric not null default 1,
  serving_unit_id uuid references public.units (id) on delete set null,
  serving_weight_grams numeric,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  calories numeric not null default 0,
  sugars numeric not null default 0,
  sodium numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Templates (frequent meals)
create table if not exists public.templates (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.template_items (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  template_id uuid not null references public.templates (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  quantity numeric not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Daily logs (one per user per day)
create table if not exists public.daily_logs (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, date)
);

-- Daily log items (nutritional snapshots so history never changes)
create table if not exists public.daily_log_items (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  daily_log_id uuid not null references public.daily_logs (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  quantity numeric not null default 1,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  calories numeric not null default 0,
  sugars numeric not null default 0,
  sodium numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Row Level Security: every table is scoped to its owner.
do $$
declare
  t text;
begin
  foreach t in array array['units', 'categories', 'brands', 'products', 'templates', 'template_items', 'daily_logs', 'daily_log_items']
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format(
      'create policy "owner select %I" on public.%I for select using (auth.uid() = user_id);', t, t
    );
    execute format(
      'create policy "owner insert %I" on public.%I for insert with check (auth.uid() = user_id);', t, t
    );
    execute format(
      'create policy "owner update %I" on public.%I for update using (auth.uid() = user_id);', t, t
    );
    execute format(
      'create policy "owner delete %I" on public.%I for delete using (auth.uid() = user_id);', t, t
    );
  end loop;
end $$;
